#################################################################
## Home Assistant Core
#################################################################

homeassistant:
  customize: !include customize.yaml
default_config:
updater:
discovery:
  ignore:
    - harmony
stream:
http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: true
  login_attempts_threshold: 10
#logger:
#  default: warn
#  logs:
#    pyatv: debug
#    custom_components.apple_tv: debug

#################################################################
## Components
#################################################################

lutron_caseta_pro:
  bridges:
    - host: lutron.network.REDACTED
      mac: !secret lutron_caseta_pro_mac
      switch: [ 17, 22 ]

wemo:
  discovery: true
  static:
    - REDACTED.220
    - REDACTED.221
    - REDACTED.222
    - REDACTED.223
    - REDACTED.225
    - REDACTED.226

webostv:
  host: 'bedroom-tv.network.REDACTED'
  name: Bedroom TV

google:
  client_id: !secret google_client_id
  client_secret: !secret goole_client_secret
  track_new_calendar: true

weather:
  - platform: darksky
    api_key: !secret darksky_api_key
    mode: daily
    name: "REDACTED, MO"

alarm_control_panel:
  - platform: manual
    name: Alarm
    code_arm_required: false
    arming_time: 30
    delay_time: 30
    trigger_time: 120
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 30
      delay_time: 30
      trigger_time: 120 
    armed_away:
      arming_time: 30
      delay_time: 15
      trigger_time: 120

route53:
  aws_access_key_id: !secret aws_access_key_id_route53
  aws_secret_access_key: !secret aws_secret_access_key_route53
  zone: !secret aws_zone_route53
  domain: !secret aws_domain_route53
  records:
    - home

camera:
  - platform: mjpeg
    name: Prusa Mini
    verify_ssl: false
    still_image_url: https://3d-printer-prusa-mini.network.REDACTED/webcam/?action=snapshot
    mjpeg_url: https://3d-printer-prusa-mini.network.REDACTED/webcam/?action=stream
  - platform: mjpeg
    name: Prusa
    verify_ssl: false
    still_image_url: https://3d-printer-prusa.network.REDACTED/webcam/?action=snapshot
    mjpeg_url: https://3d-printer-prusa.network.REDACTED/webcam/?action=stream

#################################################################
## Notifications
#################################################################

notify:
  - platform: group
    name: REDACTED_devices
    services:
      - service: mobile_app_REDACTEDs_iphone
      - service: mobile_app_REDACTED_s_ipad
      - service: mobile_app_REDACTEDs_imac

  - platform: group
    name: USER2_devices
    services:
      - service: mobile_app_USER2_s_iphone
      - service: mobile_app_USER2_s_ipad

#################################################################
## Includes
#################################################################

automation: !include_dir_merge_list automation
recorder: !include recorder.yaml
logbook: !include logbook.yaml
history: !include history.yaml
group: !include groups.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
script: !include scripts.yaml
light: !include light_group.yaml
homekit: !include homekit.yaml
switch: !include switch.yaml
emulated_hue: !include emulated_hue.yaml
cover: !include cover_group.yaml
cloud: !include cloud.yaml