#################################################################
## 3D Printer Automations
#################################################################

        ##########################################################
        ## Prusa Mini 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa Mini Print Finished
  id: '3d_printer_prusa_mini_print_finished'

  trigger:
    - platform: state
      entity_id: binary_sensor.prusa_mini_printing
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: 3D Print Complete (Prusa Mini)
        data:
          tag: prusa_mini_finished
          group: 3d_printer
          entity_id: camera.prusa_mini

        ##########################################################
        ## Prusa 3D Print Finished
        ##########################################################

- alias: 3D-Printer - Prusa Print Finished
  id: '3d_printer_prusa_print_finished'

  trigger:
    - platform: state
      entity_id: binary_sensor.prusa_printing
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 1
        seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: 3D Print Complete (Prusa)
        data:
          tag: prusa_finished
          group: 3d_printer
          entity_id: camera.prusa

        ##########################################################
        ## Power Off Prusa Mini 3D Printer When Print Complete
        ##########################################################

- alias: 3D-Printer - Power Off Prusa Mini When Print Complete
  id: '3d_printer_power_off_prusa_mini_when_print_complete'

  trigger:
    - platform: state
      entity_id: binary_sensor.prusa_mini_printing
      from: 'on'
      to: 'off'
      for:
        hours: 1
        minutes: 30
        seconds: 0

  condition:
    - condition: numeric_state
      entity_id: sensor.prusa_mini_actual_tool0_temp_celcius
      below: 25
    - condition: numeric_state
      entity_id: sensor.prusa_mini_actual_bed_temp_celcius
      below: 30
    - condition: state
      entity_id: binary_sensor.prusa_mini_printing_error
      state: 'off'
    - condition: state
      entity_id: binary_sensor.prusa_mini_printing
      state: 'off'
    - condition: state
      entity_id: switch.3d_printer_prusa_mini
      state: 'on'

  action:
    - service: notify.USER1_devices
      data:
        message: PowREDACTEDg Off 3D Printer (Prusa Mini)
        data:
          tag: prusa_mini_power_off
          group: 3d_printer
    - service: switch.turn_off
      entity_id:
        - switch.3d_printer_prusa_mini

        ##########################################################
        ## Power Off Prusa 3D Printer When Print Complete
        ##########################################################

- alias: 3D-Printer - Power Off Prusa When Print Complete
  id: '3d_printer_power_off_prusa_when_print_complete'

  trigger:
    - platform: state
      entity_id: binary_sensor.prusa_printing
      from: 'on'
      to: 'off'
      for:
        hours: 1
        minutes: 30
        seconds: 0

  condition:
    - condition: numeric_state
      entity_id: sensor.prusa_actual_tool0_temp_celcius
      below: 25
    - condition: numeric_state
      entity_id: sensor.prusa_actual_bed_temp_celcius
      below: 30
    - condition: state
      entity_id: binary_sensor.prusa_printing_error
      state: 'off'
    - condition: state
      entity_id: binary_sensor.prusa_printing
      state: 'off'
    - condition: state
      entity_id: switch.3d_printer_prusa
      state: 'on'

  action:
    - service: notify.USER1_devices
      data:
        message: PowREDACTEDg Off 3D Printer (Prusa)
        data:
          tag: prusa_power_off
          group: 3d_printer
    - service: switch.turn_off
      entity_id:
        - switch.3d_printer_prusa

        ##########################################################
        ## 3D Printer On Turn On Light
        ##########################################################

- alias: 3D-Printer - Printer On Turn On Light
  id: '3d_printer_on_turn_on_light'

  trigger:
    - platform: state
      entity_id: switch.3d_printer_prusa_mini
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
    - platform: state
      entity_id: switch.3d_printer_prusa
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: light.3d_printer_light
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.3d_printer_light

        ##########################################################
        ## 3D Printer Off Turn Off Light Prusa Mini
        ##########################################################

- alias: 3D-Printer - Printer Off Turn Off Light Prusa Mini
  id: '3d_printer_off_turn_off_light_prusa_mini'

  trigger:
    - platform: state
      entity_id: switch.3d_printer_prusa_mini
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: switch.3d_printer_prusa
      state: 'off'
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.3d_printer_light

        ##########################################################
        ## 3D Printer Off Turn Off Light Prusa
        ##########################################################

- alias: 3D-Printer - Printer Off Turn Off Light Prusa
  id: '3d_printer_off_turn_off_light_prusa'

  trigger:
    - platform: state
      entity_id: switch.3d_printer_prusa
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: switch.3d_printer_prusa_mini
      state: 'off'
    - condition: state
      entity_id: light.3d_printer_light
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.3d_printer_light

        ##########################################################
        ## 3D Printer Reload Prusa Integration After Connection
        ##########################################################

- alias: 3D-Printer - 3D Printer Reload Prusa Integration
  id: '3d_printer_reload_prusa_integration'

  trigger:
    - platform: state
      entity_id: sensor.prusa_current_state
      from: 'unavailable'
      to: 'Operational'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  action:
    - service: homeassistant.reload_config_entry
      entity_id:
        - sensor.prusa_actual_bed_temp
        - sensor.prusa_target_bed_temp
        - sensor.prusa_actual_tool0_temp
        - sensor.prusa_target_tool0_temp

        ##########################################################
        ## 3D Printer Reload Prusa Mini Integration After Connection
        ##########################################################

- alias: 3D-Printer - 3D Printer Reload Prusa Mini Integration
  id: '3d_printer_reload_prusa__mini_integration'

  trigger:
    - platform: state
      entity_id: sensor.prusa_mini_current_state
      from: 'unavailable'
      to: 'Operational'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  action:
    - service: homeassistant.reload_config_entry
      entity_id:
        - sensor.prusa_mini_actual_bed_temp
        - sensor.prusa_mini_target_bed_temp
        - sensor.prusa_mini_actual_tool0_temp
        - sensor.prusa_mini_target_tool0_temp