#################################################################
## Blinds Automations
#################################################################

        ##########################################################
        ## Close Blinds when Sun Below Horizon
        ##########################################################

- alias: Blinds - Close Blinds when Sun Below Horizon
  id: 'blinds_close_blinds_when_sun_below_horizon'

  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER2_s_office_blinds
        - cover.bedroom_closet_blinds
        - cover.stairs_blinds

#################################################################
## USER1's Office
#################################################################

        ##########################################################
        ## Open USER1's Office Blinds When Motion Detected
        ##########################################################

- alias: Blinds - USER1's Office Blinds When Motion Detected
  id: 'blinds_USER1_office_blinds_when_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.USER1s_office_motion
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: cover.USER1_s_office_blinds
      state: 'closed'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: vacuum.upstairs_roomba
      state: 'docked'
    - condition: time
      after: '08:00:00'
    - condition: numeric_state
      entity_id: sensor.REDACTED_temperature
      below: 90

  action:
    - service: cover.open_cover
      entity_id:
        - cover.USER1_s_office_blinds

        ##########################################################
        ## Close USER1's Office Blinds When No Motion Detected
        ##########################################################

- alias: Blinds - Close USER1's Office Blinds When No Motion Detected
  id: 'blinds_close_USER1_office_blinds_when_no_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.USER1s_office_motion
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.USER1_s_office_blinds
      state: 'open'
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'off'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER1_s_office_blinds

        ##########################################################
        ## Close USER1's Office Blinds When Hot Outside
        ##########################################################

- alias: Blinds - Close USER1's Office Blinds When Hot Outside
  id: 'blinds_close_USER1_office_blinds_when_hot_outside'

  trigger:
    - platform: numeric_state
      entity_id: sensor.REDACTED_temperature
      above: 90
      for:
        hours: 0
        minutes: 45
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.USER1_s_office_blinds
      state: 'open'
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'off'
    - condition: state
      entity_id: sensor.season
      state: 'summer'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER1_s_office_blinds

        ##########################################################
        ## Close USER1's Office Blinds Halfway Before Sunset
        ##########################################################

- alias: Blinds - Close USER1's Office Blinds Halfway Before Sunset
  id: 'blinds_close_USER1_office_blinds_halfway_before_sunset'

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:45:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.USER1_s_office_blinds
      state: 'open'

  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.USER1_s_office_blinds
        position: 50

        ##########################################################
        ## Close USER1's Office Blinds to 25 Before Sunset Window Closed
        ##########################################################

- alias: Blinds - Close USER1's Office Blinds to 25 Before Sunset Window Closed
  id: 'blinds_close_USER1_office_blinds_to_25_before_sunset_window_closed'

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:17:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.USER1_s_office_blinds
      state: 'open'
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'off'

  action:
    - service: cover.set_cover_position
      data:
        entity_id: cover.USER1_s_office_blinds
        position: 25

        ##########################################################
        ## Close USER1's Office Blinds to 25 Before Sunset Window Open
        ##########################################################

- alias: Blinds - Close USER1's Office Blinds to 25 Before Sunset Window Open
  id: 'blinds_close_USER1_office_blinds_to_25_before_sunset_window_open'

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:17:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.USER1_s_office_blinds
      state: 'open'
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'on'

  action:
    - service: cover.set_cover_position
      data:
        entity_id:
          - cover.USER1s_office_blinds_left
          - cover.USER1s_office_blinds_center
        position: 25

        ##########################################################
        ## Close USER1's Office Blinds when Sun Below Horizon and Window Closed
        ##########################################################

- alias: Blinds - Close USER1's Office Blinds when Sun Below Horizon and Window Closed
  id: 'blinds_close_USER1s_office_blinds_when_sun_below_horizon_window_closed'

  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'off'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER1_s_office_blinds

        ##########################################################
        ## Close USER1's Office Blinds Partially when Sun Below Horizon and Window Open
        ##########################################################

- alias: Blinds - Close USER1's Office Blinds Partially when Sun Below Horizon and Window Open
  id: 'blinds_close_USER1s_office_blinds_partially_when_sun_below_horizon_and_window_open'

  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: binary_sensor.USER1s_office_window_right
      state: 'on'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER1s_office_blinds_left
        - cover.USER1s_office_blinds_center
    - service: cover.set_cover_position
      data:
        entity_id: cover.USER1s_office_blinds_right
        position: 45

        ##########################################################
        ## Turn Off USER1's Office Lights when Blinds are Open
        ##########################################################

- alias: Blinds - Turn Off USER1's Office Lights when Blinds are Open
  id: 'blinds_turn_off_USER1_office_lights_when_blinds_are_open'

  trigger:
    - platform: state
      entity_id: cover.USER1_s_office_blinds
      from: 'closed'
      to: 'open'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: light.USER1_office_lights
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.USER1_s_office_ceiling
        - light.office_lamp

#################################################################
## Stairs
#################################################################

        ##########################################################
        ## Open Stairs Blinds When Motion Detected
        ##########################################################

- alias: Blinds - Open Stairs Blinds When Motion Detected
  id: 'blinds_stairs_blinds_open_when_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.stairs_motion
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: cover.stairs_blinds
      state: 'closed'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: vacuum.upstairs_roomba
      state: 'docked'
    - condition: numeric_state
      entity_id: sensor.REDACTED_temperature
      below: 90

  action:
    - service: cover.open_cover
      entity_id:
        - cover.stairs_blinds

        ##########################################################
        ## Close Stairs Blinds When No Motion Detected
        ##########################################################

- alias: Blinds - Close Stairs Blinds When No Motion Detected
  id: 'blinds_close_stairs_blinds_when_no_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.stairs_motion
      from: 'on'
      to: 'off'
      for:
        hours: 2
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.stairs_blinds
      state: 'open'
    - condition: state
      entity_id: binary_sensor.USER1s_office_motion
      state: 'off'
    - condition: state
      entity_id: binary_sensor.USER2s_office_motion
      state: 'off'
    - condition: state
      entity_id: binary_sensor.upstairs_bathroom_motion
      state: 'off'
    - condition: state
      entity_id: binary_sensor.stairs_motion
      state: 'off'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.stairs_blinds

        ##########################################################
        ## Close Stairs Blinds When Hot Outside
        ##########################################################

- alias: Blinds - Close Stairs Blinds When Hot Outside
  id: 'blinds_close_stairs_blinds_when_hot_outside'

  trigger:
    - platform: numeric_state
      entity_id: sensor.REDACTED_temperature
      above: 90
      for:
        hours: 0
        minutes: 45
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.stairs_blinds
      state: 'open'
    - condition: state
      entity_id: sensor.season
      state: 'summer'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.stairs_blinds

        ##########################################################
        ## Turn Off Stair Lights when Blinds are Open
        ##########################################################

- alias: Blinds - Turn Off Stair Lights when Blinds are Open
  id: 'blinds_turn_off_stair_lights_when_blinds_are_open'

  trigger:
    - platform: state
      entity_id: cover.stairs_blinds
      from: 'closed'
      to: 'open'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: light.stairs_light
      state: 'on'

  action:
    - service: light.turn_off
      entity_id:
        - light.stairs_light

#################################################################
## USER2's Office
#################################################################

        ##########################################################
        ## Open USER2's Office Blinds When Motion Detected
        ##########################################################

- alias: Blinds - USER2's Office Blinds When Motion Detected
  id: 'blinds_USER2_office_blinds_when_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.USER2s_office_motion
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: cover.USER2_s_office_blinds
      state: 'closed'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
    - condition: state
      entity_id: vacuum.upstairs_roomba
      state: 'docked'
    - condition: numeric_state
      entity_id: sensor.REDACTED_temperature
      below: 90

  action:
    - service: cover.open_cover
      entity_id:
        - cover.USER2_s_office_blinds

        ##########################################################
        ## Close USER2's Office Blinds When No Motion Detected
        ##########################################################

- alias: Blinds - Close USER2's Office Blinds When No Motion Detected
  id: 'blinds_close_USER2_office_blinds_when_no_motion_detected'

  trigger:
    - platform: state
      entity_id: binary_sensor.USER2s_office_motion
      from: 'on'
      to: 'off'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.USER2_s_office_blinds
      state: 'open'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER2_s_office_blinds

        ##########################################################
        ## Close USER2's Office Blinds When Hot Outside
        ##########################################################

- alias: Blinds - Close USER2's Office Blinds When Hot Outside
  id: 'blinds_close_USER2_office_blinds_when_hot_outside'

  trigger:
    - platform: numeric_state
      entity_id: sensor.REDACTED_temperature
      above: 90
      for:
        hours: 0
        minutes: 45
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.USER2_s_office_blinds
      state: 'open'
    - condition: state
      entity_id: sensor.season
      state: 'summer'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.USER2_s_office_blinds

#################################################################
## Bedroom
#################################################################

        ##########################################################
        ## Open Bedroom Blinds at 10a Weekdays
        ##########################################################

- alias: Blinds - Open Bedroom Blinds at 10a Weekdays
  id: 'blinds_open_bedroom_blinds_at_10a_weekdays'

  trigger:
   - platform: time
     at: '10:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'     
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: cover.open_cover
      entity_id:
        - cover.bedroom_closet_blinds

        ##########################################################
        ## Close Bedroom Blinds Before Sunset
        ##########################################################

- alias: Blinds - Close Bedroom Blinds Before Sunset
  id: 'blinds_close_bedroom_blinds_before_sunset'

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:45:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: cover.bedroom_closet_blinds
      state: 'open'

  action:
    - service: cover.close_cover
      entity_id:
        - cover.bedroom_closet_blinds

        ##########################################################
        ## Turn Off Bedroom Lights when Blinds are Open
        ##########################################################

- alias: Blinds - Turn Off Bedroom Lights when Blinds are Open
  id: 'blinds_turn_off_bedroom_lights_when_blinds_are_open'

  trigger:
    - platform: state
      entity_id: cover.bedroom_closet_blinds
      from: 'closed'
      to: 'open'

  condition:
    - condition: state
      entity_id: input_boolean.disable_blinds
      state: 'off'
    - condition: state
      entity_id: light.bedroom_lights
      state: 'on'
    - condition: not
      conditions:
      - condition: state
        entity_id: vacuum.main_floor_roomba
        state: 'cleaning'
      - condition: state
        entity_id: vacuum.main_floor_roomba
        state: 'returning'

  action:
    - service: light.turn_off
      entity_id:
        - light.bedroom_lights