#################################################################
## Bug Zapper Automations
#################################################################

        ##########################################################
        ## Turn On Bug Zapper at Sunset
        ##########################################################

- alias: Bug Zapper - Turn On Bug Zapper at Sunset
  id: 'bug_zapper_turn_on_bug_zapper_at_sunset'

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:30:00'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: switch.bug_zapper
      state: 'off'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.season
        state: 'winter'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.bug_zapper

        ##########################################################
        ## Turn Off Bug Zapper at Sunrise
        ##########################################################

- alias: Bug Zapper - Turn Off Bug Zapper at Sunrise
  id: 'bug_zapper_turn_off_bug_zapper_at_sunrise'

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '+00:15:00'

  condition:
    - condition: state
      entity_id: switch.bug_zapper
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.bug_zapper

        ##########################################################
        ## Turn Off Bug Zapper in the Rain
        ##########################################################

- alias: Bug Zapper - Turn Off Bug Zapper in the Rain
  id: 'bug_zapper_turn_off_bug_zapper_in_the_rain'

  trigger:
    - platform: state
      entity_id: weather.REDACTED
      to: 'rainy'
      for:
        hours: 0
        minutes: 30
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.bug_zapper
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.bug_zapper

        ##########################################################
        ## Turn On Bug Zapper After Rain Stops
        ##########################################################

- alias: Bug Zapper - Turn On Bug Zapper After Rain Stops
  id: 'bug_zapper_turn_on_bug_zapper_after_rain_stops'

  trigger:
    - platform: state
      entity_id: weather.REDACTED
      from: 'rainy'

  condition:
    - condition: state
      entity_id: switch.bug_zapper
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.season
        state: 'winter'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.bug_zapper

        ##########################################################
        ## Turn On Bug Zapper when Returning Home
        ##########################################################

- alias: Bug Zapper - Turn On Bug Zapper when Returning Home
  id: 'bug_zapper_turn_bug_zapper_when_returning_home'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: switch.bug_zapper
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: not
      conditions:
      - condition: state
        entity_id: weather.REDACTED
        state: 'rainy'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.season
        state: 'winter'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.bug_zapper

        ##########################################################
        ## Turn On Bug Zapper when Returning Home before Sunset
        ##########################################################

- alias: Bug Zapper - Turn On Bug Zapper when Returning Home before Sunset
  id: 'bug_zapper_turn_on_bug_zapper_when_returning_home_before_sunset'

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: switch.bug_zapper
      state: 'off'
    - condition: sun
      after: sunset
      after_offset: "-00:30:00"
    - condition: not
      conditions:
      - condition: state
        entity_id: weather.REDACTED
        state: 'rainy'
    - condition: not
      conditions:
      - condition: state
        entity_id: sensor.season
        state: 'winter'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.bug_zapper
