#################################################################
## Christmas Automations
#################################################################

        ##########################################################
        ## Turn on Exterior Christmas Lights at Sunset
        ##########################################################

- alias: Christmas - Turn on Exterior Christmas Lights at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:15:00'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.holiday
          state: 'Christmas'
        - condition: state
          entity_id: sensor.holidays_calendar
          state: "New Year's Eve"

  action:
    - service: switch.turn_on
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn Off Exterior Christmas Lights at 2a
        ##########################################################

- alias: Christmas - Turn Off Exterior Christmas Lights at 2a

  trigger:
   - platform: time
     at: '02:00:00'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn Off Exterior Christmas Lights at Sunrise
        ##########################################################

- alias: Christmas - Turn Off Exterior Christmas Lights at Sunrise

  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '+00:15:00'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn off Christmas Lights after 2a
        ##########################################################

- alias: Christmas - Turn off Christmas Lights after 2a

  trigger:
    - platform: state
      entity_id: switch.exterior_christmas_lights
      from: 'off'
      to: 'on'
      for:
        hours: 1
        minutes: 0
        seconds: 0

  condition:
    - condition: time
      after: '02:00'
      before: '07:30'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Turn on Christmas Lights when Home
        ##########################################################

- alias: Christmas - Turn on Christmas Lights when Home

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: switch.exterior_christmas_lights
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.holiday
          state: 'Christmas'
        - condition: state
          entity_id: sensor.holidays_calendar
          state: "New Year's Eve"
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.USER1_away
          state: 'on'
        - condition: state
          entity_id: input_boolean.USER2_away
          state: 'on'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.exterior_christmas_lights

        ##########################################################
        ## Christmas Tree Away Mode
        ##########################################################

- alias: Christmas - Tree Away Mode

  trigger:
    - platform: state
      entity_id: group.household
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 1
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Christmas Tree Home Mode
        ##########################################################

- alias: Christmas - Tree Home Mode

  trigger:
    - platform: state
      entity_id: group.household
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: or
      conditions:
      - condition: state
        entity_id: input_boolean.USER1_away
        state: 'on'
      - condition: state
        entity_id: input_boolean.USER2_away
        state: 'on'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree at Sunset
        ##########################################################

- alias: Christmas - Turn on Christmas Tree at Sunset

  trigger:
    - platform: sun
      event: 'sunset'
      offset: '-00:30:00'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_interior_lights_sunset
      state: 'off'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree when Sun Below Horizon
        ##########################################################

- alias: Christmas - Turn on Christmas Tree when Sun Below Horizon

  trigger:
    - platform: state
      entity_id: sun.sun
      from: 'above_horizon'
      to: 'below_horizon'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_boolean.disable_interior_lights_sunset
      state: 'off'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree when USER2 Home
        ##########################################################

- alias: Christmas - Turn on Tree when USER2 Home

  trigger:
    - platform: time
      at: '08:00:00'

  condition:
    - condition: state
      entity_id: person.USER2
      state: 'home'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn off Christmas Tree when USER2 Leaves
        ##########################################################

- alias: Christmas - Turn off Tree when USER2 Leaves

  trigger:
    - platform: state
      entity_id: person.USER2
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: time
      after: '05:00'
      before: '15:00'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree when USER2 Home
        ##########################################################

- alias: Christmas - Turn on Christmas Tree when USER2 Home

  trigger:
    - platform: state
      entity_id: person.USER2
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: time
      after: '08:30'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.USER2_away
      state: 'on'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Plex Stopped Playing Christmas Tree On
        ##########################################################

- alias: Christmas - Plex Stopped Playing Tree On

  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_appletv
      to: 'paused'
      for:
        hours: 0
        minutes: 2
        seconds: 0
    - platform: state
      entity_id: media_player.plex_living_room_appletv
      to: 'idle'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Plex Playing Christmas Tree Off
        ##########################################################

- alias: Christmas - Plex Playing Tree Off

  trigger:
    - platform: state
      entity_id: media_player.plex_living_room_appletv
      to: 'playing'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching before Midnight Christmas Tree on
        ##########################################################

- alias: Christmas - Late Night TV Watching before Midnight Tree on

  trigger:
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'paused'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'idle'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '21:30'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: switch.living_room_tv_watch_tv
      state: 'on'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching after Midnight Christmas Tree on
        ##########################################################

- alias: Christmas - Late Night TV Watching after Midnight Tree on

  trigger:
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'paused'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'idle'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: switch.living_room_tv_watch_tv
      state: 'on'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching after Midnight Christmas Tree On
        ##########################################################

- alias: Christmas - Late Night TV Watching after Midnight Tree On

  trigger:
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'paused'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'idle'
      for:
        hours: 0
        minutes: 3
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching after Midnight Christmas Tree off
        ##########################################################

- alias: Christmas - Late Night TV Watching after Midnight Tree off

  trigger:
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'playing'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '00:00'
      before: '03:00'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: switch.living_room_tv_watch_tv
      state: 'on'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Late Night TV Watching before Midnight Christmas Tree Off
        ##########################################################

- alias: Christmas - Late Night TV Watching before Midnight Tree Off

  trigger:
    - platform: state
      entity_id: media_player.living_room_appletv
      to: 'playing'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_media_lights
      state: 'off'
    - condition: time
      after: '21:30'
    - condition: state
      entity_id: input_boolean.watching_plex
      state: 'off'
    - condition: state
      entity_id: switch.living_room_tv_watch_tv
      state: 'on'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Christmas Tree Bedtime
        ##########################################################

- alias: Christmas - Tree Bedtime

  trigger:
    - platform: state
      entity_id: input_boolean.bedtime
      to: 'on'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: switch.christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn off Christmas Tree When Playing Xbox
        ##########################################################

- alias: Christmas - Turn off Christmas Tree When Playing Xbox

  trigger:
    - platform: state
      entity_id: input_select.living_room_tv_remote
      to: 'Play Xbox'
      for:
        hours: 0
        minutes: 2
        seconds: 0

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.friends_and_family
        state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '21:00:00'
      before: '05:00:00'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'on'

  action:
    - service: switch.turn_off
      entity_id:
        - switch.christmas_tree

        ##########################################################
        ## Turn on Christmas Tree When Done Playing Xbox
        ##########################################################

- alias: Christmas - Turn on Christmas Tree When Done Playing Xbox

  trigger:
    - platform: state
      entity_id: input_select.living_room_tv_remote
      from: 'Play Xbox'
      for:
        hours: 0
        minutes: 0
        seconds: 30

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: person.USER1
      state: 'home'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '21:00:00'
      before: '05:00:00'
    - condition: state
      entity_id: switch.christmas_tree
      state: 'off'

  action:
    - service: switch.turn_on
      entity_id:
        - switch.christmas_tree