#################################################################
## Door Automations
#################################################################

        ##########################################################
        ## Turn On Front Porch Lights when Front Door Opens
        ##########################################################

- alias: Doors - Turn On Front Porch Lights when Front Door Opens
  id: 'doors_turn_on_front_porch_lights_when_front_door_opens'

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 100

        ##########################################################
        ## Reset Front Porch Lights Brightness when Front Door Closes
        ##########################################################

- alias: Doors - Reset Front Porch Lights Brightness when Front Door Closes
  id: 'doors_reset_front_porch_lights_brightness_when_front_door_closes'

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_on
      entity_id:
        - light.front_porch
      data:
        brightness_pct: 50
        transition: 120

        ##########################################################
        ## Turn Off Front Porch Lights when Front Door Closes between 12-5a
        ##########################################################

- alias: Doors - Turn Off Front Porch Lights when Front Door Closes between 12-5a
  id: 'doors_turn_off_front_porch_lights_when_front_door_closes_between_12_5a'

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  condition:
    - condition: time
      after: '00:00:00'
      before: '05:00:00'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: input_select.holiday
      state: 'None'

  action:
    - service: light.turn_off
      entity_id:
        - light.front_porch
      data:
        transition: 900

        ##########################################################
        ## Turn On Living Room Lights when Front Door Opens
        ##########################################################

- alias: Doors - Turn On Living Room Lights when Front Door Opens
  id: 'doors_turn_on_living_room_lights_when_front_door_opens'

  trigger:
    - platform: state
      entity_id: binary_sensor.front_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.living_room_accent_lights
      data:
       color_temp: 447
       brightness_pct: 100

        ##########################################################
        ## Turn On Back Door Lights when Back Door Opens
        ##########################################################

- alias: Doors - Turn On Back Door Lights when Back Door Opens
  id: 'doors_turn_on_back_door_lights_when_back_door_opens'

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
       brightness_pct: 100

        ##########################################################
        ## Reset Back Door Lights Brightness when Back Door Closes
        ##########################################################

- alias: Doors - Reset Back Door Lights Brightness when Back Door Closes
  id: 'doors_reset_back_door_lights_brightness_when_back_door_closes'

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'

  action:
    - service: light.turn_on
      entity_id:
        - light.back_door
      data:
        brightness_pct: 2
        transition: 300

        ##########################################################
        ## Turn Off Back Door Lights when Back Door Closes between 12-5a
        ##########################################################

- alias: Doors - Turn Off Back Door Lights when Back Door Closes between 12-5a
  id: 'doors_turn_off_back_door_lights_when_back_door_closes_between_12_5a'

  trigger:
    - platform: state
      entity_id: binary_sensor.back_door_opened
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 17
        seconds: 0

  condition:
    - condition: time
      after: '00:00:00'
      before: '05:00:00'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: not
      conditions:
      - condition: state
        entity_id: group.friends_and_family
        state: 'home'

  action:
    - service: light.turn_off
      entity_id:
        - light.back_door
      data:
        transition: 900

        ##########################################################
        ## Turn On Basement Lights when Basement Door Opens and Lights Off
        ##########################################################

- alias: Doors - Turn On Basement Lights when Basement Door Opens and Lights Off
  id: 'doors_turn_on_basement_lights_when_basement_door_opens_and_lights_off'

  trigger:
    - platform: state
      entity_id: binary_sensor.basement_door_opened
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: light.basement_lighting
      state: 'off'
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_door_open_lights_on
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: light.turn_on
      entity_id:
        - light.basement_lights
        - light.basement_stairs
        - light.laundry_room_light
      data:
        brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.work_bench_light
      data:
       brightness_pct: 2