        ##########################################################
        ## House Guest Unlock Doors
        ##########################################################

- alias: Guest - House Guest Unlock Doors
  id: 'guest_house_guest_unlock_doors'

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.house_guest_away
      state: 'on'

  action:
    - service: lock.unlock
      entity_id:
        - lock.back_door
        - lock.front_door

        ##########################################################
        ## After Guest Home Lock Doors
        ########################################################

- alias: Guest - After Guest Home Lock Doors
  id: 'guest_after_guest_home_lock_doors'

  trigger:
    - platform: state
      entity_id: input_boolean.house_guest_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: input_boolean.disable_lock_unlock_doors
      state: 'off'
    - condition: state
      entity_id: binary_sensor.front_door_opened
      state: 'off'
    - condition: state
      entity_id: binary_sensor.back_door_opened
      state: 'off'

  action:
    - service: lock.lock
      entity_id:
        - lock.back_door
        - lock.front_door

        ##########################################################
        ## House Guest Home Turn On Lights
        ##########################################################

- alias: Guest - House Guest Turn On Lights
  id: 'guest_house_guest_turn_on_lights'

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'
    - condition: state
      entity_id: input_boolean.house_guest_away
      state: 'on'

  action:
    - service: light.turn_on
      entity_id:
        - light.kitchen_sink
        - light.living_room_lamps
        - light.dining_room_table
      data:
       color_temp: 447
       brightness_pct: 50
    - service: light.turn_on
      entity_id: light.media_center_lighting
      data:
       transition: 5
       effect: random
       brightness_pct: 75
    - service: light.turn_on
      entity_id: light.kitchen_cabinets
      data:
       brightness_pct: 2
    - service: light.turn_on
      entity_id: light.stairs_light
      data:
       brightness_pct: 50
    - service: light.turn_on
      entity_id: light.hallway_light
      data:
       brightness_pct: 25
    - service: light.turn_on
      entity_id:
        - light.front_porch
        - light.back_door
        - light.garage_light
      data:
       brightness_pct: 100
    - service: light.turn_on
      entity_id:
        - light.globe
      data:
       color_temp: 366
       brightness_pct: 20

        ##########################################################
        ## House Guest Home Reset Front Porch Lights Brightness
        ##########################################################

- alias: Guest - House Guest Reset Front Porch Lights Brightness
  id: 'guest_house_guest_reset_front_porch_lights_brightness'

  trigger:
    - platform: state
      entity_id: input_boolean.house_guest_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.front_porch
      data:
        brightness_pct: 50
        transition: 120

        ##########################################################
        ## House Guest Home Reset Back Door / Garage Lights Brightness
        ##########################################################

- alias: Guest - House Guest Reset Back Door / Garage Lights Brightness
  id: 'guest_house_guest_reset_back_door_garage_lights_brightness'

  trigger:
    - platform: state
      entity_id: input_boolean.house_guest_away
      from: 'on'
      to: 'off'

  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.disable_home_away
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.back_door
      data:
        brightness_pct: 2
        transition: 120
    - service: light.turn_on
      entity_id: light.garage_light
      data:
       brightness_pct: 2

        ##########################################################
        ## Set House Guest Away after 15 Min
        ##########################################################

- alias: Guest - Set House Guest Away after 15 Mins
  id: 'guest_set_house_guest_away_after_15_mins'

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 15
        seconds: 0

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.house_guest_away

        ##########################################################
        ## Set House Guest Home after 10 Mins
        ##########################################################

- alias: Guest - Set House Guest Home after 10 Mins
  id: 'guest_set_house_guest_home_after_10_mins'

  trigger:
    - platform: state
      entity_id: group.house_guest
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.house_guest_away

        ##########################################################
        ## Enable Guest Mode Before Midnight
        ##########################################################

- alias: Guest - Enable Guest Mode Before Midnight
  id: 'guest_enable_guest_mode_before_midnight'

  trigger:
    - platform: time
      at: '23:00:00'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: state
      entity_id: group.overnight_guests
      state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.guest_mode

        ##########################################################
        ## Enable Guest Mode after Midnight
        ##########################################################

- alias: Guest - Enable Guest Mode after Midnight
  id: 'guest_enable_guest_mode_after_midnight'

  trigger:
    - platform: state
      entity_id: group.overnight_guests
      from: 'not_home'
      to: 'home'

  condition:
    - condition: time
      after: '00:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: group.household
      state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.guest_mode

        ##########################################################
        ## Turn Off Guest Mode During the Day
        ##########################################################

- alias: Guest - Turn Off Guest Mode During the Day
  id: 'guest_turn_off_guest_mode_during_the_day'

  trigger:
    - platform: time
      at: '10:00:00'

  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.guest_mode

#################################################################
## Notifications
#################################################################

        #################################################################
        ## Guest Arrived iOS Notification
        #################################################################

- alias: Guest - Arrived iOS Notification
  id: 'guest_arrived_ios_notification'

  trigger:
    - platform: state
      entity_id: group.friends_and_family
      from: 'not_home'
      to: 'home'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Guest Arrived (Front Porch Camera)
        data:
          tag: guest
          group: guest
          entity_id: camera.front_porch
          actions:
            - action: "unlock_doors"
              title: "Unlock Doors"
              destructive: true

        ##########################################################
        ## Unlock Door for Contractors Remove when Project Done
        ##########################################################

- alias: Guest - Contractor Basement Unlock

  trigger:
   - platform: time
     at: '07:45:00'

  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri

  action:
    - service: lock.unlock
      entity_id:
        - lock.basement_door