#################################################################
## System
#################################################################

        ##########################################################
        ## Reset Overrides at 7a
        ##########################################################

- alias: System - Reset Overrides at 7a
  id: 'system_reset_overrides_at_7a'

  trigger:
   - platform: time
     at: '07:00:00'

  condition:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'off'

  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_climate
        - input_boolean.disable_notifications
        - input_boolean.disable_doorbell
        - input_boolean.disable_door_open_lights_on
        - input_boolean.disable_exterior_on_sunset
        - input_boolean.disable_exterior_off_night
        - input_boolean.disable_auto_garage
        - input_boolean.disable_home_away
        - input_boolean.disable_interior_lights_sunset
        - input_boolean.disable_lock_unlock_doors
        - input_boolean.disable_media_lights
        - input_boolean.disable_motion
        - input_boolean.disable_occupancy
        - input_boolean.disable_rainy_day
        - input_boolean.disable_water_automations
        - input_boolean.downstairs_roomba_pause
        - input_boolean.disable_startup_notifications
        - input_boolean.disable_blinds
        - input_boolean.disable_roomba
    - service: homeassistant.turn_on
      entity_id:
        - group.pihole

        ##########################################################
        ## Disable Erroneous Startup Notifications
        ##########################################################

- alias: System - Disable Erroneous Startup Notifications
  id: 'system_disable_erroneous_startup_notifications'

  trigger:
    - platform: homeassistant
      event: start

  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.disable_startup_notifications
    - delay: 00:02:00
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.disable_startup_notifications

        #################################################################
        ## Restart Bond Home Hub when Offline
        #################################################################

- alias: System - Restart Bond Home Hub when Offline
  id: 'system_restart_bond_home_hub_when_offline'

  trigger:
    - platform: state
      entity_id: binary_sensor.bond_home_hub
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 10
        seconds: 0

  action:
    - service: switch.turn_off
      entity_id:
        - switch.bond_home_hub
    - delay: 00:00:45
    - service: switch.turn_on
      entity_id:
        - switch.bond_home_hub

#################################################################
## Notifications
#################################################################

        #################################################################
        ## NAS Warning iOS Notification
        #################################################################

- alias: System - NAS Warning iOS Notification
  id: 'system_nas_warning_ios_notification'

  trigger:
    - platform: state
      entity_id: sensor.nas_status
      to: 'warning'

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: NAS RAID Failing
        data:
          tag: nas
          group: system

        ##########################################################
        ## UPS Power Loss Alert iOS Notification
        ##########################################################

- alias: System - UPS Power Loss Alert iOS Notification
  id: 'system_ups_power_loss_alert_ios_notification'

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_input_voltage
      below: 80

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Power Outage Detected
        data:
          tag: ups
          group: system

        ##########################################################
        ## UPS Power Restored Alert iOS Notification
        ##########################################################

- alias: System - UPS Power Restored Alert iOS Notification
  id: 'system_ups_power_restored_alert_ios_notification'

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_input_voltage
      above: 110

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_startup_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Power Restored
        data:
          tag: ups
          group: system

        ##########################################################
        ## UPS Low Battery Alert iOS Notification
        ##########################################################

- alias: System - UPS Low Battery Alert iOS Notification
  id: 'system_ups_low_battery_alert_ios_notification'

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_battery_charge
      below: 15

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: "UPS Battery below 15%"
        data:
          tag: ups
          group: system

        ##########################################################
        ## UPS Low Runtime Alert iOS Notification
        ##########################################################

- alias: System - UPS Low Runtime Alert iOS Notification
  id: 'system_ups_low_runtime_alert_ios_notification'

  trigger:
    - platform: numeric_state
      entity_id: sensor.ups_battery_runtime_mins
      below: 15

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: "15 mins of UPS Battery Remaining!"
        data:
          tag: ups
          group: system

        #################################################################
        ## Home Assistant Started iOS Notification
        #################################################################

- alias: System - Home Assistant Start iOS Notification
  id: 'system_home_assistant_start_ios_notification'

  trigger:
    - platform: homeassistant
      event: start

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Home Assistant Started
        data:
          tag: homeassistant
          group: system

        #################################################################
        ## Home Assistant Update iOS Notification
        #################################################################

- alias: System - Home Assistant Update iOS Notification
  id: 'system_home_assistant_update_ios_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 5
        seconds: 0

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Update Available for Home Assistant
        data:
          tag: homeassistant
          group: system

        #################################################################
        ## Bond Home Hub Offline iOS Notification
        #################################################################

- alias: System - Bond Home Hub Offline iOS Notification
  id: 'system_bond_home_hub_offline_ios_notification'

  trigger:
    - platform: state
      entity_id: binary_sensor.bond_home_hub
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 9
        seconds: 30

  condition:
    - condition: state
      entity_id: input_boolean.disable_notifications
      state: 'off'

  action:
    - service: notify.USER1_devices
      data:
        message: Bond Hub Offline. Restarting Hub
        data:
          tag: bond
          group: system